apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: REPO_URL
      type: string
  steps:
    # TODO
    # Add the following steps to your Task:
    # 1. Clone the github repo from the params into a directory called: /workspace/source
    - name: clone-repo
      image: alpine/git
      script: |
        git clone $(params.REPO_URL) /workspace/source
    # 2. Make /workspace/source your workDir and run `npm install`
    - name: install-deps
      image: node
      workingDir: /workspace/source
      script: |
        npm install
    # 3. Make /workspace/source your workDir and run `npm test`
    - name: run-tests
      image: node
      workingDir: /workspace/source
      script: |
        npm test
    # Hint: for step 2 & 3 you can use the `image: node` to run npm commands