apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
    - name: NAMESPACE
      type: string
    - name: IMAGE
      type: string
  steps:
    # TODO
    # Add the following steps to your Task:
    # 1. Run  `kubectl apply -f /workspace/intro-to-kube/tekton/k8s/nginx-deployment.yml`
    #    to the ns specified by the params
    # 2. Update the image for the deployment by running: `kubectl set image deployment/nginx-deployment nginx=<IMAGE-NAME> -n=<NAMESPACE>`
    #    specified by the image in params and ns specified in params