apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
    role: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: service
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
        role: service
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          # TODO:
          # env:
          # add POSTGRES_PASSWORD and POSTGRES_USER from the Secret
          # volumeMounts:
          # mount the postgres volume to /var/lib/postgresql/data
      #volumes:
      # mount the postgres persistent volume claim
