apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  # TODO: Configure the following values
  POSTGRES_DB: "postgresdb" # as postgresdb
  POSTGRES_USER: "admin" # as admin
  POSTGRES_PASSWORD: "psltest" # as psltest
