apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-push-deploy
spec:
  pipelineRef:
    name: build-push-deploy
  params:
    - name: REPO_URL
      value: https://github.com/BrianHHough/intro-to-kube.git