kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Developer
  namespace: dev # TODO: Re-run this file with other necessary ns
rules:
# TODO:
# target all resources with full access
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DeveloperBinding
  namespace: dev # TODO: Re-run this file with other necessary ns, match with role above
subjects:
# TODO: add Joey as target user
# note: this is case sensitive
roleRef:
# TODO: add target role to Developer