apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: namespace-c
spec:
  containers:
    - name: postgres
      image: postgres:latest
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432