name: RBAC To The Future
on:
  push:
    branches:
      - "rbac-**"

jobs:
  scavenger:
    name: RBAC To The Future 💫
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start minikube
        uses: medyagh/setup-minikube@master
        id: minikube
        with:
          driver: docker
          memory: 2048
      - name: Setup
        run: |
          kubectl create namespace dev
          kubectl create namespace staging
          kubectl create namespace prod
          kubectl create namespace database
          kubectl create namespace backup

          kubectl config set-context --current --namespace=dev
          kubectl create -f ./rbac-to-the-future/k8s/nginx-deployment.yml
          kubectl config set-context --current --namespace=staging
          kubectl create -f ./rbac-to-the-future/k8s/nginx-deployment.yml
          kubectl config set-context --current --namespace=prod
          kubectl create -f ./rbac-to-the-future/k8s/nginx-deployment.yml
          kubectl config set-context --current --namespace=database
          kubectl create -f ./rbac-to-the-future/k8s/postgres-pod.yml
          kubectl config set-context --current --namespace=backup
          kubectl create -f ./rbac-to-the-future/k8s/postgres-pod.yml

          kubectl config set-context --current --namespace=default
      - name: Create Users and Contexts
        run: |
          bash ./rbac-to-the-future/create_users.sh
      # JULES
      - name: Jules RBAC Checks
        run: |
          kubectl apply -f ./rbac-to-the-future/roles/intern.yml
          kubectl config use-context Jules-context

          FORBIDDEN=`kubectl get pods --namespace staging | echo $?`

          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot access pods in non-dev namespace"
          else
            echo "❌ Can access pods in non-dev namespace"
          fi

          FORBIDDEN=`kubectl run my-pod --image=nginx --namespace dev | echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot create/update resources in dev namespace"
          else
            echo "❌ Can create/update resources in dev namespace"
          fi

          ALLOWED=`kubectl get pods --namespace dev | echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in dev namespace"
          else
            echo "❌ Cannot access pods in dev namespace"
          fi
      # JESSICA
      - name: Jessica RBAC Checks
        run: |
          kubectl apply -f ./rbac-to-the-future/roles/db-admin/db-admin-role.yml
          kubectl apply -f ./rbac-to-the-future/roles/db-admin/db-admin-rolebinding.yml
          kubectl config use-context Jessica-context

          ALLOWED=`kubectl get pods --namespace database | echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in database namespace"
          else
            echo "❌ Cannot access pods in database namespace"
          fi

          ALLOWED=`kubectl run my-pod --image=nginx --namespace database | echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in database namespace"
          else
            echo "❌ Cannot create pods in database namespace"
          fi

          ALLOWED=`kubectl delete pod my-pod --namespace database | echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can delete resources in database namespace"
          else
            echo "❌ Cannot delete resources in database namespace"
          fi

          FORBIDDEN=`kubectl get pods --namespace dev | echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot get resources in non-database namespace"
          else
            echo "❌ Can get resources in non-database namespace"
          fi

          FORBIDDEN=`kubectl get pods --namespace dev | echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot create/update resources in non-database namespace"
          else
            echo "❌ Can create/update resources in non-database namespace"
          fi