name: RBAC To The Future
on:
  push:
    branches:
      - "rbac-**"

jobs:
  scavenger:
    name: RBAC To The Future 💫
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start minikube
        uses: medyagh/setup-minikube@master
        id: minikube
        with:
          driver: docker
          memory: 2048
      - name: Setup
        run: |
          bash ./rbac-to-the-future/setup.sh
      - name: Create Users and Contexts
        run: |
          bash ./rbac-to-the-future/create_users.sh
      # JULES
      - name: Jules RBAC Checks
        run: |
          kubectl config use-context minikube
          kubectl apply -f ./rbac-to-the-future/roles/intern.yml
          kubectl config use-context Jules-context

          FORBIDDEN=`kubectl get pods --namespace staging &>/dev/null; echo $?`

          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot access pods in non-dev namespace"
          else
            echo "❌ Can access pods in non-dev namespace"
          fi

          FORBIDDEN=`kubectl run my-pod --image=nginx --namespace dev &>/dev/null; echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot create/update resources in dev namespace"
          else
            echo "❌ Can create/update resources in dev namespace"
          fi

          ALLOWED=`kubectl get pods --namespace dev &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in dev namespace"
          else
            echo "❌ Cannot access pods in dev namespace"
          fi
      # JESSICA
      - name: Jessica RBAC Checks
        run: |
          kubectl config use-context minikube
          kubectl apply -f ./rbac-to-the-future/roles/db-admin.yml

          NS=`cat ./rbac-to-the-future/roles/db-admin.yml | grep namespace -m 1 | grep 'database' -o`
          if [ "$NS" == "database" ]; then
            OTHER_NS="backup"
          else
            NS="backup"
            OTHER_NS="database"
          fi 

          echo "NAMESPACES"
          echo "------------------------"
          echo $NS
          echo $OTHER_NS
          echo "------------------------"
          sed "s/$NS/$OTHER_NS/g" ./rbac-to-the-future/roles/db-admin.yml > ./rbac-to-the-future/roles/db-admin-next.yml
          kubectl apply -f ./rbac-to-the-future/roles/db-admin-next.yml

          kubectl config use-context Jessica-context

          ALLOWED=`kubectl get pods --namespace database &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in database namespace"
          else
            echo "❌ Cannot access pods in database namespace"
          fi

          ALLOWED=`kubectl get pods --namespace backup &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in backup namespace"
          else
            echo "❌ Cannot access pods in backup namespace"
          fi

          ALLOWED=`kubectl run my-pod --image=nginx --namespace database &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in database namespace"
          else
            echo "❌ Cannot create pods in database namespace"
          fi

           ALLOWED=`kubectl run my-pod --image=nginx --namespace backup &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in backup namespace"
          else
            echo "❌ Cannot create pods in backup namespace"
          fi

          # Wait for pods to get created
          sleep 6

          ALLOWED=`kubectl delete pod my-pod --namespace database &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can delete resources in database namespace"
          else
            echo "❌ Cannot delete resources in database namespace"
          fi

          ALLOWED=`kubectl delete pod my-pod --namespace backup &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can delete resources in backup namespace"
          else
            echo "❌ Cannot delete resources in backup namespace"
          fi

          FORBIDDEN=`kubectl get pods --namespace dev &>/dev/null; echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot get resources in namespaces other than database or backup"
          else
            echo "❌ Can get resources in namespaces other than database or backup"
          fi

          FORBIDDEN=`kubectl run my-pod --image=nginx --namespace dev &>/dev/null; echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot create/update resources in namespaces other than database or backup"
          else
            echo "❌ Can create/update resources in namespaces other than database or backup"
          fi
      # JOEY
      - name: Joey RBAC Checks
        run: |
          kubectl config use-context minikube
          kubectl apply -f ./rbac-to-the-future/roles/developer.yml

          NS=`cat ./rbac-to-the-future/roles/developer.yml | grep namespace -m 1 | grep 'dev' -o`
          if [ "$NS" == "dev" ]; then
            SECOND_NS="staging"
            THIRD_NS="prod"
          else
            NS=`cat ./rbac-to-the-future/roles/developer.yml | grep namespace -m 1 | grep 'staging' -o`
            if [ "$NS" == "staging" ]; then
              SECOND_NS="dev"
              THIRD_NS="prod"
            else
              NS="prod"
              SECOND_NS="dev"
              THIRD_NS="staging"
            fi
          fi
          echo "NAMESPACES"
          echo "------------------------"
          echo $NS
          echo $SECOND_NS
          echo $THIRD_NS
          echo "------------------------"

          sed "s/$NS/$SECOND_NS/g"  ./rbac-to-the-future/roles/developer.yml >  ./rbac-to-the-future/roles/developer-second.yml
          sed "s/$NS/$THIRD_NS/g"  ./rbac-to-the-future/roles/developer.yml >  ./rbac-to-the-future/roles/developer-third.yml

          kubectl apply -f ./rbac-to-the-future/roles/developer-second.yml
          kubectl apply -f ./rbac-to-the-future/roles/developer-third.yml

          kubectl config use-context Joey-context

          ALLOWED=`kubectl get pods --namespace dev &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in dev namespace"
          else
            echo "❌ Cannot access pods in dev namespace"
          fi

          ALLOWED=`kubectl get pods --namespace staging &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in staging namespace"
          else
            echo "❌ Cannot access pods in staging namespace"
          fi

          ALLOWED=`kubectl get pods --namespace prod &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in prod namespace"
          else
            echo "❌ Cannot access pods in prod namespace"
          fi

          ALLOWED=`kubectl run my-pod --image=nginx --namespace dev &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in dev namespace"
          else
            echo "❌ Cannot create pods in dev namespace"
          fi

          ALLOWED=`kubectl run my-pod --image=nginx --namespace staging &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in staging namespace"
          else
            echo "❌ Cannot create pods in staging namespace"
          fi

          ALLOWED=`kubectl run my-pod --image=nginx --namespace prod &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in prod namespace"
          else
            echo "❌ Cannot create pods in prod namespace"
          fi
          
          # Wait for pods to get created
          sleep 6

          FORBIDDEN=`kubectl delete pod my-pod --namespace dev &>/dev/null; echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot delete resources in dev namespace"
          else
            echo "❌ Can delete resources in dev namespace"
          fi

          FORBIDDEN=`kubectl delete pod my-pod --namespace staging &>/dev/null; echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot delete resources in staging namespace"
          else
            echo "❌ Can delete resources in staging namespace"
          fi

          FORBIDDEN=`kubectl delete pod my-pod --namespace prod &>/dev/null; echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot delete resources in prod namespace"
          else
            echo "❌ Can delete resources in prod namespace"
          fi

          FORBIDDEN=`kubectl get pods --namespace database &>/dev/null; echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot get resources in namespaces other than dev, staging or prod"
          else
            echo "❌ Can get resources in namespaces other than dev, staging or prod"
          fi

          FORBIDDEN=`kubectl run my-pod --image=nginx --namespace database &>/dev/null; echo $?`
          if [ "$FORBIDDEN" == "1" ]; then
            echo "✅ Cannot create/update resources in namespaces other than dev, staging or prod"
          else
            echo "❌ Can create/update resources in namespaces other than dev, staging or prod"
          fi
      # JESUS
      - name: Jesus RBAC Checks
        run: |
          kubectl config use-context minikube
          kubectl apply -f ./rbac-to-the-future/roles/kube-admin.yml
          kubectl config use-context Jesus-context

          ALLOWED=`kubectl get pods --namespace dev &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in dev namespace"
          else
            echo "❌ Cannot access pods in dev namespace"
          fi

          ALLOWED=`kubectl get pods --namespace staging &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in staging namespace"
          else
            echo "❌ Cannot access pods in staging namespace"
          fi

          ALLOWED=`kubectl get pods --namespace prod &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in prod namespace"
          else
            echo "❌ Cannot access pods in prod namespace"
          fi

          ALLOWED=`kubectl get pods --namespace database &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in database namespace"
          else
            echo "❌ Cannot access pods in database namespace"
          fi

          ALLOWED=`kubectl get pods --namespace backup &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can access pods in backup namespace"
          else
            echo "❌ Cannot access pods in backup namespace"
          fi

          # Adding more waits
          sleep 6

          ALLOWED=`kubectl run pod-1 --image=nginx --namespace dev &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in dev namespace"
          else
            echo "❌ Cannot create pods in dev namespace"
          fi

          ALLOWED=`kubectl run pod-2 --image=nginx --namespace staging &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in staging namespace"
          else
            echo "❌ Cannot create pods in staging namespace"
          fi

          ALLOWED=`kubectl run pod-3 --image=nginx --namespace prod &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in prod namespace"
          else
            echo "❌ Cannot create pods in prod namespace"
          fi

          ALLOWED=`kubectl run pod-4 --image=nginx --namespace database &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in database namespace"
          else
            echo "❌ Cannot create pods in database namespace"
          fi

          ALLOWED=`kubectl run pod-5 --image=nginx --namespace backup &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can create pods in backup namespace"
          else
            echo "❌ Cannot create pods in backup namespace"
          fi

          # Wait for pods to get created
          sleep 6

          ALLOWED=`kubectl delete pod pod-1 --namespace dev &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can delete resources in dev namespace"
          else
            echo "❌ Cannot delete resources in dev namespace"
          fi

          ALLOWED=`kubectl delete pod pod-2 --namespace staging &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can delete resources in staging namespace"
          else
            echo "❌ Cannot delete resources in staging namespace"
          fi

          ALLOWED=`kubectl delete pod pod-3 --namespace prod &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can delete resources in prod namespace"
          else
            echo "❌ Cannot delete resources in prod namespace"
          fi

          ALLOWED=`kubectl delete pod pod-4 --namespace database &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can delete resources in database namespace"
          else
            echo "❌ Cannot delete resources in database namespace"
          fi

          ALLOWED=`kubectl delete pod pod-5 --namespace backup &>/dev/null; echo $?`
          if [ "$ALLOWED" == "0" ]; then
            echo "✅ Can delete resources in backup namespace"
          else
            echo "❌ Cannot delete resources in backup namespace"
          fi
